package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"example/web-service-gin/graph"
	"example/web-service-gin/graph/model"
	"fmt"
)

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context, page *model.PageArgs) (*model.RolePage, error) {
	panic(fmt.Errorf("not implemented: Test - test"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
